# Site settings
title: La Bulle Crypto
description: Le podcast francophone sur l'actualité des cryptomonnaies !
cover: assets/images/main.svg
logo: assets/images/logo.svg
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "http://www.labullecrypto.com" # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

# Social
facebook: labullecrypto
twitter: labullecrypto
youtube: UC_nTxNcaB_HXDt9hv13ugHg
telegram: BPCby0LDFPYTUhYNDlILVg
soundcloud: la-bulle-crypto
iTunes: fr/podcast/la-bulle/id1281121446
discord: kXQM7NY
rss: labullecrypto

permalink: /:title

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

collections:
  news:
    output: true
    permalink: /nouvelle/:name
  episodes:
    output: true
    permalink: /episode/:name
  meetups:
    output: true
    permalink: /meetup/:name
  fiches:
    output: true
    permalink: /fiche/:name
  donates:
    output: true
    permalink: /donate/:name

defaults:
  - scope:
      path: ""
      type: news
    values:
      layout: news_item
      type: news
      cover: assets/images/chancellor.png
      credits_username: test
      credits_name: testname
      overlay: true
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
      type: episode
      cover: assets/images/episode.jpg
      credits_username: innov8
      credits_name: Matthieu A
      overlay: true
  - scope:
      path: ""
      type: meetups
    values:
      layout: meetup
      type: meetup
      cover: assets/images/meetups.jpg
      credits_username: danteov_seen
      credits_name: Nikola Jovanovic
      overlay: true
  - scope:
      path: ""
      type: fiches
    values:
      layout: fiche
      type: fiche
      cover: assets/images/fiches.jpg
      credits_username: samuelzeller
      credits_name: Samuel Zeller
      overlay: true
  - scope:
      path: ""
      type: donates
    values:
      layout: donate

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: adrienthiery #github username
repo: hanuman #github repository
branch: master #branch
relative_source: ./ #source directory
destination: dist/ #destination directory
production_url:  http://www.labullecrypto.com/
source_url:  https://github.com/adrienthiery/labullecrypto.com #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
